# This is a basic workflow to help you get started with Actions

name: Newman Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install Newman
        run: npm install -g newman

      - name: Install Newman and Newman HTML Reporter
        run: npm install -g newman newman-reporter-html

      - name: Create reports directory
        run: mkdir -p postman-tests/reports

      - name: Run Newman tests
        run: newman run apis_test.json -r cli,json,html --reporter-json-export reports/report.json --reporter-html-export reports/report.html
